"""Initial migration

Revision ID: a47e9dc8a2d0
Revises: 
Create Date: 2025-09-08 22:45:25.816531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47e9dc8a2d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settle_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'LOCKED', 'SETTLED', 'CANCELLED', name='roundstatus'), nullable=False),
    sa.Column('result', sa.Enum('UP', 'DOWN', 'VOID', name='roundresult'), nullable=True),
    sa.Column('commit_hash', sa.Text(), nullable=True),
    sa.Column('reveal', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_rounds_code', 'rounds', ['code'], unique=False)
    op.create_index('ix_rounds_status', 'rounds', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.Enum('UP', 'DOWN', name='betside'), nullable=False),
    sa.Column('stake_u', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PLACED', 'LOST', 'WON', 'REFUNDED', name='betstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bets_round_user', 'bets', ['round_id', 'user_id'], unique=False)
    op.create_index('ix_bets_status', 'bets', ['status'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('amount_u', sa.BigInteger(), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_account_user', 'ledger_entries', ['account', 'user_id'], unique=False)
    op.create_index('ix_ledger_ref', 'ledger_entries', ['ref_type', 'ref_id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', name='transfertype'), nullable=False),
    sa.Column('amount_u', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', name='transferstatus'), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transfers_status', 'transfers', ['status'], unique=False)
    op.create_index('ix_transfers_user_id', 'transfers', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chain', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    op.drop_index('ix_transfers_user_id', table_name='transfers')
    op.drop_index('ix_transfers_status', table_name='transfers')
    op.drop_table('transfers')
    op.drop_index('ix_ledger_ref', table_name='ledger_entries')
    op.drop_index('ix_ledger_account_user', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_bets_status', table_name='bets')
    op.drop_index('ix_bets_round_user', table_name='bets')
    op.drop_table('bets')
    op.drop_table('users')
    op.drop_index('ix_rounds_status', table_name='rounds')
    op.drop_index('ix_rounds_code', table_name='rounds')
    op.drop_table('rounds')
    # ### end Alembic commands ###